sequenceDiagram
  title Transação
  participant Cliente
  participant Loyalt
  participant Comerciante
  Cliente->Loyalt: Cadastra chave de transação
  Comerciante->Loyalt: Cadastra campanha cashback
  Cliente->Comerciante: Faz o pagamento pelo serviço
  Comerciante->Loyalt: Realiza a transação de cashback
  Loyalt-->Loyalt: Realiza o processamento da transação <br/> conforme campanha configurada
  Loyalt-->Loyalt: Credita valor na conta relacionada ao cliente x comercio
  Cliente-->Loyalt: Visualiza o credito na conta